export interface Internship {
  id: string;
  company: string;
  role: string;
  type: "paid" | "free";
  stipend: string;
  duration: string;
  location: string;
  mode: "remote" | "onsite" | "hybrid";
  skills: string[];
  description: string;
  eligibility: string;
  deadline: string;
  applyUrl: string;
  season: "summer" | "winter" | "year-round";
  rating: number;
  tags: string[];
}

export const INTERNSHIP_DATABASE: Internship[] = [
  // ─── GOOGLE ───
  { id: "g1", company: "Google", role: "Software Engineering Intern", type: "paid", stipend: "₹80,000/month + housing", duration: "12 weeks", location: "Bangalore / Hyderabad", mode: "onsite", skills: ["Java", "Python", "C++", "Data Structures", "Algorithms"], description: "Work on real Google projects alongside full-time engineers. Mentorship from senior Googlers. Past projects include Google Search, Android, Cloud, and YouTube features.", eligibility: "Pre-final / Final year B.Tech/BCA/MCA students", deadline: "Rolling", applyUrl: "https://buildyourfuture.withgoogle.com/internships", season: "summer", rating: 4.8, tags: ["FAANG", "Tech Giant", "PPO"] },
  { id: "g2", company: "Google", role: "UX Design Intern", type: "paid", stipend: "₹75,000/month + housing", duration: "12 weeks", location: "Hyderabad", mode: "onsite", skills: ["Figma", "Prototyping", "User Research", "Design Thinking", "Material Design"], description: "Contribute to design projects across Google products. Work with UX researchers and product managers to create intuitive user experiences.", eligibility: "Design / HCI students with portfolio", deadline: "Rolling", applyUrl: "https://buildyourfuture.withgoogle.com/internships", season: "summer", rating: 4.7, tags: ["FAANG", "Design", "UX"] },
  { id: "g3", company: "Google", role: "Cloud Engineering Intern", type: "paid", stipend: "₹85,000/month + housing", duration: "12 weeks", location: "Bangalore", mode: "onsite", skills: ["Cloud Computing", "Linux", "Networking", "Python", "Kubernetes"], description: "Work on Google Cloud Platform infrastructure. Deploy, monitor, and optimize cloud services used by millions of businesses.", eligibility: "CS / IT students with cloud coursework", deadline: "Rolling", applyUrl: "https://buildyourfuture.withgoogle.com/internships", season: "summer", rating: 4.6, tags: ["FAANG", "Cloud", "GCP"] },

  // ─── MICROSOFT ───
  { id: "ms1", company: "Microsoft", role: "Software Engineering Intern", type: "paid", stipend: "₹70,000/month", duration: "12 weeks", location: "Hyderabad / Noida", mode: "onsite", skills: ["C#", ".NET", "TypeScript", "React", "Azure"], description: "Build features for products used by billions — Windows, Office, Azure, Teams. Work in agile teams with code reviews and production deployments.", eligibility: "Pre-final year B.Tech/BCA students", deadline: "Rolling", applyUrl: "https://careers.microsoft.com/v2/global/en/internships", season: "summer", rating: 4.7, tags: ["FAANG", "Tech Giant", "PPO"] },
  { id: "ms2", company: "Microsoft", role: "AI/ML Research Intern", type: "paid", stipend: "₹90,000/month", duration: "16 weeks", location: "Hyderabad", mode: "onsite", skills: ["Python", "PyTorch", "TensorFlow", "NLP", "Computer Vision"], description: "Work with Microsoft Research on cutting-edge AI projects. Potential for paper publications and patents.", eligibility: "M.Tech/PhD in CS/EE with ML background", deadline: "Rolling", applyUrl: "https://careers.microsoft.com/v2/global/en/internships", season: "summer", rating: 4.8, tags: ["FAANG", "Research", "AI/ML", "PPO"] },
  { id: "ms3", company: "Microsoft", role: "Program Manager Intern", type: "paid", stipend: "₹65,000/month", duration: "12 weeks", location: "Hyderabad", mode: "onsite", skills: ["Product Management", "Data Analysis", "SQL", "PowerPoint", "Agile"], description: "Define product vision, write specs, analyze data, and ship features. Work closely with engineering and design teams.", eligibility: "B.Tech / MBA students with PM interest", deadline: "Rolling", applyUrl: "https://careers.microsoft.com/v2/global/en/internships", season: "summer", rating: 4.5, tags: ["FAANG", "PM", "Non-technical"] },

  // ─── AMAZON ───
  { id: "a1", company: "Amazon", role: "Software Development Engineering Intern", type: "paid", stipend: "₹75,000/month + relocation", duration: "12 weeks", location: "Bangalore / Hyderabad", mode: "onsite", skills: ["Java", "Python", "DSA", "AWS", "System Design"], description: "Ship production code for Amazon services. Own a project end-to-end with mentorship from SDE II+ engineers.", eligibility: "Pre-final year B.Tech students", deadline: "Rolling", applyUrl: "https://www.amazon.jobs/en/teams/internships", season: "summer", rating: 4.6, tags: ["FAANG", "E-commerce", "AWS", "PPO"] },
  { id: "a2", company: "Amazon", role: "Data Science Intern", type: "paid", stipend: "₹70,000/month", duration: "12 weeks", location: "Bangalore", mode: "onsite", skills: ["Python", "SQL", "Machine Learning", "Statistics", "Pandas"], description: "Build ML models for recommendations, fraud detection, or demand forecasting. Work with petabytes of data.", eligibility: "Stats/CS/ML students with Python experience", deadline: "Rolling", applyUrl: "https://www.amazon.jobs/en/teams/internships", season: "summer", rating: 4.5, tags: ["FAANG", "Data Science", "ML"] },
  { id: "a3", company: "Amazon", role: "Operations Intern", type: "paid", stipend: "₹45,000/month", duration: "8 weeks", location: "Multiple cities", mode: "onsite", skills: ["Excel", "Data Analysis", "Process Optimization", "SQL"], description: "Optimize Amazon's logistics and supply chain operations. Work on real problems affecting millions of deliveries daily.", eligibility: "B.Tech / BBA / MBA students", deadline: "Rolling", applyUrl: "https://www.amazon.jobs/en/teams/internships", season: "summer", rating: 4.2, tags: ["FAANG", "Operations", "Non-technical"] },

  // ─── META ───
  { id: "m1", company: "Meta", role: "Software Engineering Intern", type: "paid", stipend: "₹95,000/month + housing + relocation", duration: "12 weeks", location: "Remote (India)", mode: "remote", skills: ["Python", "C++", "React", "GraphQL", "Distributed Systems"], description: "Work on Facebook, Instagram, WhatsApp, or Reality Labs. Ship code that reaches billions of users.", eligibility: "CS students with strong coding skills", deadline: "Rolling", applyUrl: "https://metacareers.com/internships", season: "summer", rating: 4.9, tags: ["FAANG", "Social Media", "Remote", "PPO"] },
  { id: "m2", company: "Meta", role: "Data Science Intern", type: "paid", stipend: "₹90,000/month + housing", duration: "12 weeks", location: "Remote (India)", mode: "remote", skills: ["Python", "SQL", "A/B Testing", "Statistics", "Pandas"], description: "Analyze user behavior patterns, design experiments, and provide data-driven insights for product decisions.", eligibility: "Stats/CS/Math students", deadline: "Rolling", applyUrl: "https://metacareers.com/internships", season: "summer", rating: 4.7, tags: ["FAANG", "Data Science", "Remote"] },

  // ─── TCS ───
  { id: "t1", company: "TCS", role: "TCS Digital Intern", type: "paid", stipend: "₹15,000/month", duration: "6 months", location: "Pan India", mode: "onsite", skills: ["Java", "Python", "Web Development", "SQL", "Cloud Basics"], description: "Work on enterprise projects across banking, retail, and healthcare domains. Structured training with live project exposure.", eligibility: "B.Tech/BCA students in pre-final year", deadline: "Rolling", applyUrl: "https://www.tcs.com/careers", season: "year-round", rating: 3.8, tags: ["Mass Recruiter", "Training", "India"] },
  { id: "t2", company: "TCS", role: "TCS Research Intern", type: "paid", stipend: "₹25,000/month", duration: "6 months", location: "Chennai / Pune", mode: "onsite", skills: ["Python", "AI/ML", "NLP", "Research", "Paper Writing"], description: "Work with TCS Research on published research projects. Potential for paper publications and patent filings.", eligibility: "M.Tech/PhD students", deadline: "Rolling", applyUrl: "https://www.tcs.com/careers", season: "year-round", rating: 4.0, tags: ["Research", "AI/ML", "India"] },
  { id: "t3", company: "TCS", role: "TCS Smart Intern (Unpaid)", type: "free", stipend: "Unpaid (certificate + PPO chance)", duration: "4-8 weeks", location: "Pan India", mode: "onsite", skills: ["Basic Programming", "Web Development", "Excel"], description: "Entry-level internship for freshers. Learn enterprise development processes, attend training sessions, and work on guided projects.", eligibility: "Any UG student", deadline: "Rolling", applyUrl: "https://www.tcs.com/careers", season: "year-round", rating: 3.5, tags: ["Unpaid", "Entry-level", "Certificate"] },

  // ─── INFOSYS ───
  { id: "i1", company: "Infosys", role: "HackWithInfy Intern", type: "paid", stipend: "₹20,000/month", duration: "3 months", location: "Bangalore / Mysore", mode: "onsite", skills: ["Java", "Python", "DSA", "Web Development"], description: "Selected through HackWithInfy programming contest. Work on Infosys projects with mentorship from senior architects.", eligibility: "B.Tech students who cleared HackWithInfy", deadline: "May-June annually", applyUrl: "https://www.infosys.com/careers/internships.html", season: "summer", rating: 4.0, tags: ["Coding Contest", "India", "PPO"] },
  { id: "i2", company: "Infosys", role: "Infosys Springboard Intern", type: "free", stipend: "Unpaid (stipend for top performers)", duration: "6-8 weeks", location: "Remote", mode: "remote", skills: ["Basic Programming", "SQL", "HTML/CSS", "Python"], description: "Virtual internship program with mentorship and project work. Learn industry practices and build a portfolio project.", eligibility: "Pre-final year UG students", deadline: "Rolling", applyUrl: "https://springboard.infosys.com/", season: "year-round", rating: 3.8, tags: ["Unpaid", "Remote", "Entry-level"] },
  { id: "i3", company: "Infosys", role: "Infosys Data Science Intern", type: "paid", stipend: "₹22,000/month", duration: "3 months", location: "Bangalore", mode: "onsite", skills: ["Python", "Machine Learning", "SQL", "Data Visualization", "Pandas"], description: "Work on data analytics and ML projects within Infosys's consulting practice. Real client data and business problems.", eligibility: "CS/DS/ML students", deadline: "Rolling", applyUrl: "https://www.infosys.com/careers/internships.html", season: "year-round", rating: 3.9, tags: ["Data Science", "India"] },

  // ─── FLIPKART ───
  { id: "f1", company: "Flipkart", role: "Software Development Intern", type: "paid", stipend: "₹50,000/month", duration: "6 months", location: "Bangalore", mode: "onsite", skills: ["Java", "React", "Microservices", "SQL", "Redis"], description: "Work on India's largest e-commerce platform. Contribute to search, payments, logistics, or seller tools.", eligibility: "B.Tech CS/IT students", deadline: "Rolling", applyUrl: "https://www.flipkart.com/careers", season: "year-round", rating: 4.4, tags: ["E-commerce", "India", "Startup Culture"] },
  { id: "f2", company: "Flipkart", role: "Data Science Intern", type: "paid", stipend: "₹45,000/month", duration: "6 months", location: "Bangalore", mode: "onsite", skills: ["Python", "ML", "SQL", "Recommendation Systems", "A/B Testing"], description: "Build ML models for product recommendations, price optimization, and demand forecasting at massive scale.", eligibility: "CS/Stats/Math students with ML knowledge", deadline: "Rolling", applyUrl: "https://www.flipkart.com/careers", season: "year-round", rating: 4.3, tags: ["E-commerce", "Data Science", "India"] },

  // ─── RAZORPAY ───
  { id: "r1", company: "Razorpay", role: "Full Stack Intern", type: "paid", stipend: "₹35,000/month", duration: "6 months", location: "Bangalore", mode: "hybrid", skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "Redis"], description: "Build fintech products used by 8M+ businesses. Work on payments, banking, or lending products.", eligibility: "B.Tech students with web dev experience", deadline: "Rolling", applyUrl: "https://razorpay.com/careers/", season: "year-round", rating: 4.3, tags: ["Fintech", "Startup", "India"] },

  // ─── ATLAN ───
  { id: "at1", company: "Atlan", role: "Engineering Intern", type: "paid", stipend: "₹40,000/month", duration: "6 months", location: "Remote", mode: "remote", skills: ["React", "TypeScript", "GraphQL", "PostgreSQL"], description: "Work on the data governance platform loved by data teams worldwide. Ship features used by data engineers at Netflix, Snap, and more.", eligibility: "Students with strong frontend/backend skills", deadline: "Rolling", applyUrl: "https://atlan.com/careers/", season: "year-round", rating: 4.5, tags: ["Data", "Remote", "Startup"] },

  // ─── ADOBE ───
  { id: "ad1", company: "Adobe", role: "Computer Science Intern", type: "paid", stipend: "₹60,000/month", duration: "6 months", location: "Bangalore", mode: "onsite", skills: ["Java", "C++", "JavaScript", "React", "Cloud"], description: "Work on creative tools like Photoshop, Premiere Pro, or Adobe Experience Cloud. Collaborate with world-class engineers.", eligibility: "Pre-final year B.Tech/M.Tech students", deadline: "Rolling", applyUrl: "https://adobe.com/careers", season: "summer", rating: 4.6, tags: ["Creative", "Product", "PPO"] },
  { id: "ad2", company: "Adobe", role: "Design Intern", type: "paid", stipend: "₹55,000/month", duration: "6 months", location: "Bangalore", mode: "onsite", skills: ["Figma", "Sketch", "Prototyping", "Motion Design", "Design Systems"], description: "Contribute to Adobe's design systems and creative products. Work with the UX team on user research and testing.", eligibility: "Design / Architecture / HCI students", deadline: "Rolling", applyUrl: "https://adobe.com/careers", season: "summer", rating: 4.5, tags: ["Design", "Creative", "PPO"] },

  // ─── NVIDIA ───
  { id: "n1", company: "NVIDIA", role: "AI Engineering Intern", type: "paid", stipend: "₹80,000/month", duration: "12 weeks", location: "Bangalore / Pune", mode: "onsite", skills: ["C++", "Python", "CUDA", "Deep Learning", "Computer Vision"], description: "Work on GPU-accelerated AI and deep learning frameworks. Contribute to CUDA, TensorRT, or autonomous driving projects.", eligibility: "CS/EE students with systems programming experience", deadline: "Rolling", applyUrl: "https://nvidia.com/careers", season: "summer", rating: 4.7, tags: ["AI/ML", "Hardware", "GPU", "Deep Tech"] },

  // ─── WALMART ───
  { id: "w1", company: "Walmart", role: "Tech Intern", type: "paid", stipend: "₹40,000/month", duration: "6 months", location: "Bangalore / Chennai", mode: "onsite", skills: ["Java", "Spring Boot", "React", "Microservices", "Docker"], description: "Work on Walmart's e-commerce platform and supply chain tech. Contribute to features used by 250M+ customers globally.", eligibility: "B.Tech CS/IT students", deadline: "Rolling", applyUrl: "https://careers.walmart.com/", season: "year-round", rating: 4.2, tags: ["E-commerce", "Retail", "Global"] },

  // ─── SAP ───
  { id: "sap1", company: "SAP", role: "Software Engineering Intern", type: "paid", stipend: "₹35,000/month", duration: "6 months", location: "Bangalore", mode: "hybrid", skills: ["Java", "JavaScript", "React", "ABAP", "Cloud Foundry"], description: "Work on enterprise software solutions used by 440,000+ companies. Contribute to S/4HANA or SAP Cloud Platform.", eligibility: "B.Tech/M.Tech CS/IT students", deadline: "Rolling", applyUrl: "https://sap.com/careers", season: "year-round", rating: 4.1, tags: ["Enterprise", "ERP", "Germany"] },

  // ─── NVIDIA (unpaid/free) ───
  { id: "n2", company: "NVIDIA", role: "Research Volunteer (Unpaid)", type: "free", stipend: "Unpaid (publication opportunity)", duration: "3-6 months", location: "Remote", mode: "remote", skills: ["Python", "PyTorch", "Deep Learning", "Research"], description: "Work with NVIDIA research teams on published papers. Get mentored by senior researchers. No stipend but strong recommendation letter.", eligibility: "M.Tech/PhD students with ML publications", deadline: "Rolling", applyUrl: "https://nvidia.com/careers", season: "year-round", rating: 4.3, tags: ["Unpaid", "Research", "Publication"] },

  // ─── UNICORN STARTUPS ───
  { id: "u1", company: "Zerodha", role: "Backend Engineering Intern", type: "paid", stipend: "₹30,000/month", duration: "3-6 months", location: "Bangalore", mode: "onsite", skills: ["Python", "Django", "Go", "PostgreSQL", "Redis"], description: "Work on India's largest stock brokerage platform. Handle millions of trades per day with sub-second latency.", eligibility: "Students with backend dev experience", deadline: "Rolling", applyUrl: "https://zerodha.com/careers/", season: "year-round", rating: 4.6, tags: ["Fintech", "Startup", "India"] },
  { id: "u2", company: "Cred", role: "Full Stack Intern", type: "paid", stipend: "₹45,000/month", duration: "6 months", location: "Bangalore", mode: "onsite", skills: ["React", "Node.js", "TypeScript", "Go", "Redis"], description: "Build premium fintech products for credit-worthy Indians. Work on credit scoring, payments, or rewards platform.", eligibility: "B.Tech students with full-stack skills", deadline: "Rolling", applyUrl: "https://cred.club/careers", season: "year-round", rating: 4.4, tags: ["Fintech", "Startup", "India"] },
  { id: "u3", company: "Swiggy", role: "ML Engineering Intern", type: "paid", stipend: "₹40,000/month", duration: "6 months", location: "Bangalore", mode: "onsite", skills: ["Python", "ML", "Supply Chain Optimization", "SQL", "Spark"], description: "Build ML models for delivery routing, demand prediction, and restaurant ranking. Impact millions of daily orders.", eligibility: "CS/ML students with Python experience", deadline: "Rolling", applyUrl: "https://careers.swiggy.com/", season: "year-round", rating: 4.3, tags: ["Food Tech", "ML", "India"] },
  { id: "u4", company: "Meesho", role: "SDE Intern", type: "paid", stipend: "₹35,000/month", duration: "6 months", location: "Bangalore", mode: "onsite", skills: ["Java", "Go", "React", "MySQL", "Microservices"], description: "Work on India's fastest growing e-commerce platform. Handle 1B+ monthly page views and massive catalog data.", eligibility: "B.Tech CS/IT students", deadline: "Rolling", applyUrl: "https://meesho.com/careers", season: "year-round", rating: 4.2, tags: ["E-commerce", "Startup", "India"] },

  // ─── INTERNATIONAL ───
  { id: "in1", company: "Goldman Sachs", role: "Technology Summer Analyst", type: "paid", stipend: "₹1,20,000/month", duration: "10 weeks", location: "Bangalore", mode: "onsite", skills: ["Python", "Java", "SQL", "Data Structures", "Finance Basics"], description: "Work on trading platforms, risk models, or data engineering at Goldman Sachs. One of the highest-paying internships in India.", eligibility: "B.Tech/B.Sc CS/Math/Stats students", deadline: "March annually", applyUrl: "https://goldmansachs.com/careers", season: "summer", rating: 4.7, tags: ["Finance", "Investment Bank", "High Pay"] },
  { id: "in2", company: "JP Morgan", role: "Software Engineering Intern", type: "paid", stipend: "₹1,00,000/month", duration: "10 weeks", location: "Bangalore / Mumbai", mode: "onsite", skills: ["Python", "Java", "Spring Boot", "AWS", "Kafka"], description: "Build systems for one of the world's largest banks. Work on trading, risk management, or payments infrastructure.", eligibility: "B.Tech CS/IT students", deadline: "February annually", applyUrl: "https://jpmorganchase.com/careers", season: "summer", rating: 4.6, tags: ["Finance", "Investment Bank", "High Pay"] },
  { id: "in3", company: "Bloomberg", role: "Software Engineering Intern", type: "paid", stipend: "₹90,000/month + relocation", duration: "12 weeks", location: "London / NYC (sponsored)", mode: "onsite", skills: ["C++", "Python", "DSA", "Finance", "Distributed Systems"], description: "Work on Bloomberg Terminal — the most influential financial software. Solve hard problems in real-time data processing.", eligibility: "CS students with strong C++ skills", deadline: "Rolling", applyUrl: "https://bloomberg.com/careers", season: "summer", rating: 4.8, tags: ["Finance", "International", "C++", "High Pay"] },

  // ─── OPEN SOURCE / NON-PROFIT ───
  { id: "os1", company: "GSOC (Google)", role: "Open Source Intern", type: "paid", stipend: "$3,000-$6,000 (based on country)", duration: "12-22 weeks", location: "Remote", mode: "remote", skills: ["Git", "Python", "JavaScript", "Linux", "Open Source"], description: "Contribute to open source projects mentored by organizations like Mozilla, Python, KDE, and more. Build your GitHub profile.", eligibility: "Students aged 18+ enrolled in recognized institution", deadline: "March annually", applyUrl: "https://summerofcode.withgoogle.com/", season: "summer", rating: 4.8, tags: ["Open Source", "Remote", "International", "Prestigious"] },
  { id: "os2", company: "MLH Fellowship", role: "Open Source Fellow", type: "paid", stipend: "$5,000-$7,000 per batch", duration: "12 weeks", location: "Remote", mode: "remote", skills: ["JavaScript", "Python", "Web Dev", "Open Source", "Git"], description: "Work on open source projects with top tech companies as sponsors. Build your portfolio and get hired by Fellows alumni network.", eligibility: "Students and recent grads", deadline: "Rolling", applyUrl: "https://fellowship.mlh.io/", season: "year-round", rating: 4.7, tags: ["Open Source", "Remote", "Community"] },

  // ─── MORE PAID STARTUPS ───
  { id: "u5", company: "Razorpay", role: "DevOps Intern", type: "paid", stipend: "₹30,000/month", duration: "6 months", location: "Bangalore", mode: "hybrid", skills: ["Docker", "Kubernetes", "AWS", "Terraform", "CI/CD"], description: "Build and maintain infrastructure for India's leading payment gateway. Work on automation, monitoring, and deployment pipelines.", eligibility: "Students with Linux and cloud experience", deadline: "Rolling", applyUrl: "https://razorpay.com/careers/", season: "year-round", rating: 4.2, tags: ["Fintech", "DevOps", "India"] },
  { id: "u6", company: "PhonePe", role: "SDE Intern", type: "paid", stipend: "₹40,000/month", duration: "6 months", location: "Bangalore", mode: "onsite", skills: ["Java", "Go", "Microservices", "Kafka", "Redis"], description: "Work on India's largest UPI payments platform. Handle billions of transactions with zero downtime.", eligibility: "B.Tech CS/IT students", deadline: "Rolling", applyUrl: "https://phonepe.com/careers/", season: "year-round", rating: 4.3, tags: ["Fintech", "Payments", "India"] },
  { id: "u7", company: "Freshworks", role: "SDE Intern", type: "paid", stipend: "₹30,000/month", duration: "6 months", location: "Chennai", mode: "onsite", skills: ["Ruby on Rails", "React", "JavaScript", "PostgreSQL", "Redis"], description: "Work on Freshdesk, Freshsales, or Freshservice products. Build SaaS products used by 60,000+ businesses globally.", eligibility: "B.Tech CS/IT students", deadline: "Rolling", applyUrl: "https://freshworks.com/careers/", season: "year-round", rating: 4.2, tags: ["SaaS", "Startup", "India"] },
  { id: "u8", company: "Zoho", role: "SDE Intern", type: "paid", stipend: "₹25,000/month", duration: "6 months", location: "Chennai", mode: "onsite", skills: ["Java", "JavaScript", "React", "Python", "Angular"], description: "Work on Zoho's 50+ SaaS products. Bootstrapped, profitable, and employee-first culture with no VC pressure.", eligibility: "B.Tech/BCA students", deadline: "Rolling", applyUrl: "https://www.zoho.com/careers/", season: "year-round", rating: 4.4, tags: ["SaaS", "Bootstrapped", "India"] },
  { id: "u9", company: "Postman", role: "Engineering Intern", type: "paid", stipend: "₹50,000/month", duration: "6 months", location: "Remote (India)", mode: "remote", skills: ["JavaScript", "React", "Node.js", "Electron", "API Design"], description: "Work on the world's most popular API development platform. Build features used by 20M+ developers.", eligibility: "Students with web dev experience", deadline: "Rolling", applyUrl: "https://postman.com/careers/", season: "year-round", rating: 4.5, tags: ["Developer Tools", "Remote", "Global"] },
];

export function getInternshipsByCompany(company: string): Internship[] {
  return INTERNSHIP_DATABASE.filter(i => i.company.toLowerCase() === company.toLowerCase());
}

export function getInternshipsByType(type: "paid" | "free"): Internship[] {
  return INTERNSHIP_DATABASE.filter(i => i.type === type);
}

export function getInternshipsBySkills(skills: string[]): Internship[] {
  const lower = skills.map(s => s.toLowerCase());
  return INTERNSHIP_DATABASE.filter(i =>
    i.skills.some(s => lower.some(l => s.toLowerCase().includes(l) || l.includes(s.toLowerCase())))
  );
}

export function searchInternships(query: string): Internship[] {
  const q = query.toLowerCase();
  return INTERNSHIP_DATABASE.filter(i =>
    i.company.toLowerCase().includes(q) ||
    i.role.toLowerCase().includes(q) ||
    i.skills.some(s => s.toLowerCase().includes(q)) ||
    i.tags.some(t => t.toLowerCase().includes(q))
  );
}
