import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const INTERNSHIPS = [
  // FAANG + Big Tech
  {
    title: "Software Engineering Intern",
    company: "Google",
    companyLogo: "https://logo.clearbit.com/google.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹80,000/month",
    stipendMin: 80000,
    stipendMax: 80000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "Full Stack",
    description: "Work on core Google products used by billions. You'll collaborate with senior engineers to design, develop, and ship features across Google's product suite.",
    requirements: JSON.stringify(["Strong CS fundamentals", "Experience with at least one programming language", "Problem-solving skills"]),
    skillsRequired: JSON.stringify(["Python", "Java", "C++", "Data Structures", "Algorithms", "System Design"]),
    applyUrl: "https://careers.google.com",
    openings: 50,
    isPPO: true,
    isCertified: true,
    mentorAvailable: true,
    lorAvailable: true,
    difficulty: "hard",
    acceptanceRate: 0.03,
    competitionLevel: "extreme",
    companyRating: 4.6,
    internshipRating: 4.7,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Go", "Java", "Python", "gRPC", "Borg", "Bigtable"]),
    interviewRounds: 5,
    deadline: new Date("2026-09-15"),
  },
  {
    title: "Machine Learning Intern",
    company: "Microsoft",
    companyLogo: "https://logo.clearbit.com/microsoft.com",
    location: "Hyderabad, India",
    city: "Hyderabad",
    country: "India",
    type: "paid",
    stipend: "₹75,000/month",
    stipendMin: 75000,
    stipendMax: 75000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "AI/ML",
    description: "Join Microsoft's AI platform team to build next-generation ML models and tools. Work on Azure AI services that power intelligent applications worldwide.",
    requirements: JSON.stringify(["ML/DL fundamentals", "Python proficiency", "Research experience preferred"]),
    skillsRequired: JSON.stringify(["Python", "PyTorch", "TensorFlow", "Machine Learning", "Deep Learning", "SQL"]),
    applyUrl: "https://careers.microsoft.com",
    openings: 30,
    isPPO: true,
    isCertified: true,
    mentorAvailable: true,
    lorAvailable: true,
    difficulty: "hard",
    acceptanceRate: 0.05,
    competitionLevel: "extreme",
    companyRating: 4.5,
    internshipRating: 4.6,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Python", "PyTorch", "Azure", "Cognitive Services", "ONNX"]),
    interviewRounds: 4,
    deadline: new Date("2026-08-30"),
  },
  {
    title: "Frontend Developer Intern",
    company: "Amazon",
    companyLogo: "https://logo.clearbit.com/amazon.com",
    location: "Chennai, India",
    city: "Chennai",
    country: "India",
    type: "paid",
    stipend: "₹70,000/month",
    stipendMin: 70000,
    stipendMax: 70000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "onsite",
    domain: "Frontend",
    description: "Build customer-facing features for Amazon's e-commerce platform. Focus on performance, accessibility, and beautiful user experiences at massive scale.",
    requirements: JSON.stringify(["Web development experience", "React or equivalent", "CS fundamentals"]),
    skillsRequired: JSON.stringify(["JavaScript", "React", "TypeScript", "HTML/CSS", "Node.js", "AWS"]),
    applyUrl: "https://amazon.jobs",
    openings: 40,
    isPPO: true,
    isCertified: true,
    mentorAvailable: true,
    lorAvailable: true,
    difficulty: "hard",
    acceptanceRate: 0.04,
    competitionLevel: "extreme",
    companyRating: 4.3,
    internshipRating: 4.4,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["React", "JavaScript", "AWS", "DynamoDB", "CloudFront"]),
    interviewRounds: 4,
    deadline: new Date("2026-08-15"),
  },
  {
    title: "AI Research Intern",
    company: "NVIDIA",
    companyLogo: "https://logo.clearbit.com/nvidia.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹90,000/month",
    stipendMin: 90000,
    stipendMax: 90000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "onsite",
    domain: "AI/ML",
    description: "Research cutting-edge deep learning techniques at NVIDIA's AI lab. Work on GPU-accelerated ML, computer vision, or NLP projects with potential for publication.",
    requirements: JSON.stringify(["Strong ML background", "PyTorch experience", "Research publications preferred"]),
    skillsRequired: JSON.stringify(["Python", "PyTorch", "CUDA", "Deep Learning", "Computer Vision", "NLP"]),
    applyUrl: "https://nvidia.com/careers",
    openings: 15,
    isPPO: true,
    isCertified: true,
    lorAvailable: true,
    difficulty: "hard",
    acceptanceRate: 0.05,
    competitionLevel: "extreme",
    companyRating: 4.7,
    internshipRating: 4.8,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Python", "PyTorch", "CUDA", "TensorRT", "NGC"]),
    interviewRounds: 4,
    deadline: new Date("2026-09-01"),
  },
  {
    title: "Data Science Intern",
    company: "Meta",
    companyLogo: "https://logo.clearbit.com/meta.com",
    location: "Remote, India",
    city: "Remote",
    country: "India",
    type: "paid",
    stipend: "₹85,000/month",
    stipendMin: 85000,
    stipendMax: 85000,
    currency: "INR",
    duration: "12 weeks",
    durationWeeks: 12,
    workMode: "remote",
    domain: "Data Science",
    description: "Analyze massive datasets to drive product decisions at Meta. Work with product teams to identify growth opportunities and optimize user experiences.",
    requirements: JSON.stringify(["SQL proficiency", "Python/R", "Statistical analysis", "A/B testing knowledge"]),
    skillsRequired: JSON.stringify(["Python", "SQL", "Pandas", "Statistics", "A/B Testing", "Data Visualization"]),
    applyUrl: "https://metacareers.com",
    openings: 25,
    isPPO: true,
    isCertified: true,
    difficulty: "hard",
    acceptanceRate: 0.04,
    competitionLevel: "extreme",
    companyRating: 4.4,
    internshipRating: 4.5,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Python", "SQL", "Presto", "Pandas", "Jupyter"]),
    interviewRounds: 4,
    deadline: new Date("2026-08-20"),
  },
  // Indian Tech Giants
  {
    title: "Full Stack Developer Intern",
    company: "Zoho",
    companyLogo: "https://logo.clearbit.com/zoho.com",
    location: "Chennai, India",
    city: "Chennai",
    country: "India",
    type: "paid",
    stipend: "₹25,000/month",
    stipendMin: 25000,
    stipendMax: 25000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "onsite",
    domain: "Full Stack",
    description: "Build enterprise SaaS products used by millions. At Zoho, interns work on real features that ship to production. Strong mentorship culture.",
    requirements: JSON.stringify(["Web development basics", "Any programming language", "Willingness to learn"]),
    skillsRequired: JSON.stringify(["JavaScript", "React", "Node.js", "Python", "SQL", "HTML/CSS"]),
    applyUrl: "https://zoho.com/careers",
    openings: 100,
    isPPO: true,
    isCertified: true,
    mentorAvailable: true,
    difficulty: "medium",
    acceptanceRate: 0.15,
    competitionLevel: "medium",
    companyRating: 4.2,
    internshipRating: 4.3,
    source: "curated",
    category: "tech",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["JavaScript", "React", "Node.js", "PostgreSQL", "Java"]),
    interviewRounds: 3,
    deadline: new Date("2026-07-30"),
  },
  {
    title: "Software Development Intern",
    company: "Freshworks",
    companyLogo: "https://logo.clearbit.com/freshworks.com",
    location: "Chennai, India",
    city: "Chennai",
    country: "India",
    type: "paid",
    stipend: "₹20,000/month",
    stipendMin: 20000,
    stipendMax: 20000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "Full Stack",
    description: "Join Freshworks' engineering team to build SaaS products for customer service, IT, and marketing. Work in an agile environment with frequent releases.",
    requirements: JSON.stringify(["Programming fundamentals", "Web development basics"]),
    skillsRequired: JSON.stringify(["JavaScript", "Ruby", "React", "SQL", "REST APIs"]),
    applyUrl: "https://freshworks.com/careers",
    openings: 40,
    isPPO: true,
    isCertified: true,
    difficulty: "medium",
    acceptanceRate: 0.12,
    competitionLevel: "medium",
    companyRating: 4.1,
    internshipRating: 4.2,
    source: "curated",
    category: "tech",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Ruby on Rails", "React", "PostgreSQL", "Redis", "AWS"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-01"),
  },
  {
    title: "Backend Developer Intern",
    company: "Atlassian",
    companyLogo: "https://logo.clearbit.com/atlassian.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹55,000/month",
    stipendMin: 55000,
    stipendMax: 55000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "Backend",
    description: "Work on Jira, Confluence, or Bitbucket backend services. Build distributed systems that help millions of teams collaborate effectively.",
    requirements: JSON.stringify(["Java or Kotlin", "CS fundamentals", "API design knowledge"]),
    skillsRequired: JSON.stringify(["Java", "Kotlin", "REST APIs", "Microservices", "SQL", "Docker"]),
    applyUrl: "https://atlassian.com/careers",
    openings: 20,
    isPPO: true,
    isCertified: true,
    mentorAvailable: true,
    lorAvailable: true,
    difficulty: "hard",
    acceptanceRate: 0.08,
    competitionLevel: "high",
    companyRating: 4.5,
    internshipRating: 4.6,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Java", "Kotlin", "Spring Boot", "Kafka", "Kubernetes"]),
    interviewRounds: 4,
    deadline: new Date("2026-09-10"),
  },
  // Indian IT Services
  {
    title: "AI/ML Engineering Intern",
    company: "TCS",
    companyLogo: "https://logo.clearbit.com/tcs.com",
    location: "Chennai, India",
    city: "Chennai",
    country: "India",
    type: "paid",
    stipend: "₹15,000/month",
    stipendMin: 15000,
    stipendMax: 15000,
    currency: "INR",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "onsite",
    domain: "AI/ML",
    description: "Work with TCS's AI research division on natural language processing, computer vision, and predictive analytics projects for enterprise clients.",
    requirements: JSON.stringify(["Python basics", "ML fundamentals"]),
    skillsRequired: JSON.stringify(["Python", "Machine Learning", "TensorFlow", "NLP", "Data Analysis"]),
    applyUrl: "https://tcs.com/careers",
    openings: 200,
    isPPO: true,
    isCertified: true,
    difficulty: "easy",
    acceptanceRate: 0.25,
    competitionLevel: "medium",
    companyRating: 3.8,
    internshipRating: 3.9,
    source: "curated",
    category: "tech",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Python", "TensorFlow", "NLP", "Spark", "Hadoop"]),
    interviewRounds: 2,
    deadline: new Date("2026-07-25"),
  },
  {
    title: "Cloud Engineering Intern",
    company: "Infosys",
    companyLogo: "https://logo.clearbit.com/infosys.com",
    location: "Pune, India",
    city: "Pune",
    country: "India",
    type: "paid",
    stipend: "₹12,000/month",
    stipendMin: 12000,
    stipendMax: 12000,
    currency: "INR",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "onsite",
    domain: "Cloud",
    description: "Learn cloud architecture and DevOps practices at Infosys's Cloud Campus. Work on AWS/Azure migrations and infrastructure automation.",
    requirements: JSON.stringify(["Basic networking knowledge", "Linux fundamentals"]),
    skillsRequired: JSON.stringify(["AWS", "Azure", "Docker", "Linux", "Python", "Terraform"]),
    applyUrl: "https://infosys.com/careers",
    openings: 150,
    isPPO: true,
    isCertified: true,
    difficulty: "easy",
    acceptanceRate: 0.30,
    competitionLevel: "low",
    companyRating: 3.7,
    internshipRating: 3.8,
    source: "curated",
    category: "tech",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["AWS", "Azure", "Docker", "Kubernetes", "Terraform"]),
    interviewRounds: 2,
    deadline: new Date("2026-07-28"),
  },
  // Startups
  {
    title: "React Developer Intern",
    company: "Razorpay",
    companyLogo: "https://logo.clearbit.com/razorpay.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹30,000/month",
    stipendMin: 30000,
    stipendMax: 30000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "Frontend",
    description: "Build the checkout experience for India's largest fintech platform. Ship code that processes billions of transactions. Fast-paced startup culture.",
    requirements: JSON.stringify(["React experience", "JavaScript proficiency", "CSS skills"]),
    skillsRequired: JSON.stringify(["React", "TypeScript", "JavaScript", "HTML/CSS", "Redux", "REST APIs"]),
    applyUrl: "https://razorpay.com/careers",
    openings: 15,
    isPPO: true,
    isCertified: true,
    mentorAvailable: true,
    difficulty: "medium",
    acceptanceRate: 0.10,
    competitionLevel: "high",
    companyRating: 4.3,
    internshipRating: 4.4,
    source: "curated",
    category: "startup",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["React", "TypeScript", "Node.js", "MongoDB", "Redis"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-10"),
  },
  {
    title: "Backend Intern",
    company: "CRED",
    companyLogo: "https://logo.clearbit.com/cred.club",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹40,000/month",
    stipendMin: 40000,
    stipendMax: 40000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "Backend",
    description: "Work on CRED's payment infrastructure and credit score platform. Build high-performance microservices handling millions of daily transactions.",
    requirements: JSON.stringify(["Go or Java", "Distributed systems knowledge", "CS fundamentals"]),
    skillsRequired: JSON.stringify(["Go", "Java", "Microservices", "PostgreSQL", "Redis", "Kafka"]),
    applyUrl: "https://cred.club/careers",
    openings: 10,
    isPPO: true,
    isCertified: true,
    difficulty: "hard",
    acceptanceRate: 0.08,
    competitionLevel: "high",
    companyRating: 4.2,
    internshipRating: 4.3,
    source: "curated",
    category: "startup",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Go", "Java", "Kafka", "Redis", "PostgreSQL"]),
    interviewRounds: 4,
    deadline: new Date("2026-08-05"),
  },
  {
    title: "ML Engineer Intern",
    company: "PhonePe",
    companyLogo: "https://logo.clearbit.com/phonepe.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹35,000/month",
    stipendMin: 35000,
    stipendMax: 35000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "AI/ML",
    description: "Build ML models for fraud detection, recommendation systems, and user personalization at India's largest UPI platform.",
    requirements: JSON.stringify(["Python", "ML fundamentals", "SQL"]),
    skillsRequired: JSON.stringify(["Python", "Machine Learning", "SQL", "TensorFlow", "Feature Engineering"]),
    applyUrl: "https://phonepe.com/careers",
    openings: 12,
    isPPO: true,
    isCertified: true,
    difficulty: "medium",
    acceptanceRate: 0.10,
    competitionLevel: "high",
    companyRating: 4.1,
    internshipRating: 4.2,
    source: "curated",
    category: "startup",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Python", "TensorFlow", "Kafka", "Spark", "Kubernetes"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-15"),
  },
  {
    title: "DevOps Intern",
    company: "Flipkart",
    companyLogo: "https://logo.clearbit.com/flipkart.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹30,000/month",
    stipendMin: 30000,
    stipendMax: 30000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "onsite",
    domain: "DevOps",
    description: "Work on Flipkart's infrastructure automation, CI/CD pipelines, and cloud operations. Support India's largest e-commerce platform during peak traffic events.",
    requirements: JSON.stringify(["Linux basics", "Scripting knowledge", "Interest in infrastructure"]),
    skillsRequired: JSON.stringify(["Linux", "Docker", "Kubernetes", "Jenkins", "Python", "AWS"]),
    applyUrl: "https://flipkart.com/careers",
    openings: 20,
    isPPO: true,
    isCertified: true,
    difficulty: "medium",
    acceptanceRate: 0.12,
    competitionLevel: "medium",
    companyRating: 4.0,
    internshipRating: 4.1,
    source: "curated",
    category: "tech",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Docker", "Kubernetes", "Jenkins", "Ansible", "AWS"]),
    interviewRounds: 3,
    deadline: new Date("2026-07-20"),
  },
  // Global Companies
  {
    title: "iOS Developer Intern",
    company: "Apple",
    companyLogo: "https://logo.clearbit.com/apple.com",
    location: "Hyderabad, India",
    city: "Hyderabad",
    country: "India",
    type: "paid",
    stipend: "₹75,000/month",
    stipendMin: 75000,
    stipendMax: 75000,
    currency: "INR",
    duration: "12 weeks",
    durationWeeks: 12,
    workMode: "onsite",
    domain: "Mobile",
    description: "Work on iOS frameworks and apps at Apple's Hyderabad development center. Contribute to the next generation of Apple's mobile experiences.",
    requirements: JSON.stringify(["Swift proficiency", "iOS development experience", "UI/UX sensibility"]),
    skillsRequired: JSON.stringify(["Swift", "UIKit", "SwiftUI", "Xcode", "Core Data", "REST APIs"]),
    applyUrl: "https://apple.com/careers",
    openings: 10,
    isPPO: true,
    isCertified: true,
    difficulty: "hard",
    acceptanceRate: 0.04,
    competitionLevel: "extreme",
    companyRating: 4.7,
    internshipRating: 4.8,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "slow",
    techStack: JSON.stringify(["Swift", "SwiftUI", "Xcode", "Core ML", "ARKit"]),
    interviewRounds: 5,
    deadline: new Date("2026-09-20"),
  },
  {
    title: "Software Engineer Intern",
    company: "Adobe",
    companyLogo: "https://logo.clearbit.com/adobe.com",
    location: "Noida, India",
    city: "Noida",
    country: "India",
    type: "paid",
    stipend: "₹50,000/month",
    stipendMin: 50000,
    stipendMax: 50000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "Full Stack",
    description: "Work on Adobe Creative Cloud products. Build features for Photoshop, Illustrator, or Premiere Pro used by millions of creatives worldwide.",
    requirements: JSON.stringify(["Java or C++", "Web technologies", "CS fundamentals"]),
    skillsRequired: JSON.stringify(["Java", "JavaScript", "React", "C++", "Node.js", "TypeScript"]),
    applyUrl: "https://adobe.com/careers",
    openings: 25,
    isPPO: true,
    isCertified: true,
    mentorAvailable: true,
    lorAvailable: true,
    difficulty: "hard",
    acceptanceRate: 0.06,
    competitionLevel: "high",
    companyRating: 4.4,
    internshipRating: 4.5,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Java", "JavaScript", "React", "C++", "Electron"]),
    interviewRounds: 4,
    deadline: new Date("2026-08-25"),
  },
  {
    title: "Data Analyst Intern",
    company: "Uber",
    companyLogo: "https://logo.clearbit.com/uber.com",
    location: "Hyderabad, India",
    city: "Hyderabad",
    country: "India",
    type: "paid",
    stipend: "₹60,000/month",
    stipendMin: 60000,
    stipendMax: 60000,
    currency: "INR",
    duration: "12 weeks",
    durationWeeks: 12,
    workMode: "hybrid",
    domain: "Data Science",
    description: "Analyze ride-sharing data to optimize pricing, routing, and driver incentives. Work with one of the world's largest real-time datasets.",
    requirements: JSON.stringify(["SQL proficiency", "Python", "Statistical analysis"]),
    skillsRequired: JSON.stringify(["SQL", "Python", "Tableau", "Statistics", "A/B Testing", "Pandas"]),
    applyUrl: "https://uber.com/careers",
    openings: 15,
    isPPO: true,
    isCertified: true,
    difficulty: "hard",
    acceptanceRate: 0.06,
    competitionLevel: "high",
    companyRating: 4.3,
    internshipRating: 4.4,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Python", "SQL", "Presto", "Tableau", "Jupyter"]),
    interviewRounds: 4,
    deadline: new Date("2026-08-10"),
  },
  // Government / Research
  {
    title: "Research Intern — Quantum Computing",
    company: "IISc Bangalore",
    companyLogo: "",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹20,000/month",
    stipendMin: 20000,
    stipendMax: 20000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "onsite",
    domain: "Research",
    description: "Work with IISc's quantum computing lab on quantum algorithms, error correction, and quantum machine learning. Opportunity to publish research papers.",
    requirements: JSON.stringify(["Physics or CS background", "Linear algebra", "Programming skills"]),
    skillsRequired: JSON.stringify(["Python", "Qiskit", "Linear Algebra", "Quantum Computing", "NumPy"]),
    applyUrl: "https://iisc.ac.in",
    openings: 5,
    isPPO: false,
    isCertified: true,
    lorAvailable: true,
    difficulty: "hard",
    acceptanceRate: 0.10,
    competitionLevel: "medium",
    companyRating: 4.8,
    internshipRating: 4.9,
    source: "curated",
    category: "research",
    hiringSpeed: "slow",
    techStack: JSON.stringify(["Python", "Qiskit", "Cirq", "NumPy", "SciPy"]),
    interviewRounds: 2,
    deadline: new Date("2026-08-01"),
  },
  {
    title: "Cybersecurity Intern",
    company: "DRDO",
    companyLogo: "",
    location: "Delhi, India",
    city: "Delhi",
    country: "India",
    type: "paid",
    stipend: "₹15,000/month",
    stipendMin: 15000,
    stipendMax: 15000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "onsite",
    domain: "Cybersecurity",
    description: "Work with DRDO's cyber defense division on network security, vulnerability assessment, and penetration testing for national defense systems.",
    requirements: JSON.stringify(["Cybersecurity knowledge", "Networking fundamentals", "Security clearance eligible"]),
    skillsRequired: JSON.stringify(["Networking", "Linux", "Python", "Penetration Testing", "Wireshark", "Nmap"]),
    applyUrl: "https://drdo.gov.in",
    openings: 8,
    isPPO: false,
    isCertified: true,
    lorAvailable: true,
    isGovt: true,
    difficulty: "medium",
    acceptanceRate: 0.15,
    competitionLevel: "medium",
    companyRating: 4.5,
    internshipRating: 4.4,
    source: "curated",
    category: "government",
    hiringSpeed: "slow",
    techStack: JSON.stringify(["Linux", "Python", "Wireshark", "Metasploit", "Kali"]),
    interviewRounds: 2,
    deadline: new Date("2026-07-31"),
  },
  // More diverse options
  {
    title: "UI/UX Design Intern",
    company: "Swiggy",
    companyLogo: "https://logo.clearbit.com/swiggy.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹25,000/month",
    stipendMin: 25000,
    stipendMax: 25000,
    currency: "INR",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "hybrid",
    domain: "UI/UX",
    description: "Design user experiences for India's food delivery platform. Conduct user research, create prototypes, and work closely with product engineers.",
    requirements: JSON.stringify(["Figma proficiency", "Design portfolio", "UX research basics"]),
    skillsRequired: JSON.stringify(["Figma", "Prototyping", "User Research", "Wireframing", "Design Systems"]),
    applyUrl: "https://swiggy.com/careers",
    openings: 8,
    isPPO: true,
    isCertified: true,
    difficulty: "medium",
    acceptanceRate: 0.08,
    competitionLevel: "high",
    companyRating: 4.1,
    internshipRating: 4.2,
    source: "curated",
    category: "startup",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Figma", "Maze", "Hotjar", "Principle"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-01"),
  },
  {
    title: "Blockchain Developer Intern",
    company: "Polygon",
    companyLogo: "https://logo.clearbit.com/polygon.technology",
    location: "Remote, India",
    city: "Remote",
    country: "India",
    type: "paid",
    stipend: "₹35,000/month",
    stipendMin: 35000,
    stipendMax: 35000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "remote",
    domain: "Blockchain",
    description: "Work on Layer 2 scaling solutions for Ethereum. Build smart contracts, develop dApps, and contribute to blockchain infrastructure at Polygon.",
    requirements: JSON.stringify(["Solidity knowledge", "Web3 understanding", "JavaScript"]),
    skillsRequired: JSON.stringify(["Solidity", "Ethereum", "JavaScript", "Smart Contracts", "Web3.js", "Hardhat"]),
    applyUrl: "https://polygon.technology/careers",
    openings: 8,
    isPPO: true,
    isCertified: true,
    difficulty: "hard",
    acceptanceRate: 0.08,
    competitionLevel: "high",
    companyRating: 4.3,
    internshipRating: 4.4,
    source: "curated",
    category: "startup",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Solidity", "Hardhat", "Web3.js", "Ethers.js", "IPFS"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-20"),
  },
  {
    title: "QA Automation Intern",
    company: "Wipro",
    companyLogo: "https://logo.clearbit.com/wipro.com",
    location: "Coimbatore, India",
    city: "Coimbatore",
    country: "India",
    type: "paid",
    stipend: "₹10,000/month",
    stipendMin: 10000,
    stipendMax: 10000,
    currency: "INR",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "onsite",
    domain: "QA",
    description: "Learn test automation frameworks and quality assurance practices. Write automated tests for enterprise applications at Wipro's quality engineering division.",
    requirements: JSON.stringify(["Programming basics", "Interest in testing"]),
    skillsRequired: JSON.stringify(["Java", "Selenium", "TestNG", "API Testing", "Postman"]),
    applyUrl: "https://wipro.com/careers",
    openings: 80,
    isPPO: true,
    isCertified: true,
    difficulty: "easy",
    acceptanceRate: 0.35,
    competitionLevel: "low",
    companyRating: 3.6,
    internshipRating: 3.7,
    source: "curated",
    category: "tech",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Java", "Selenium", "TestNG", "Maven", "Jenkins"]),
    interviewRounds: 2,
    deadline: new Date("2026-07-20"),
  },
  {
    title: "Android Developer Intern",
    company: "Ola",
    companyLogo: "https://logo.clearbit.com/olacabs.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹25,000/month",
    stipendMin: 25000,
    stipendMax: 25000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "Mobile",
    description: "Build features for Ola's ride-hailing Android app used by millions. Work on maps integration, real-time tracking, and payment flows.",
    requirements: JSON.stringify(["Kotlin/Java", "Android basics", "Git"]),
    skillsRequired: JSON.stringify(["Kotlin", "Android SDK", "Jetpack Compose", "REST APIs", "MVVM", "Git"]),
    applyUrl: "https://olacabs.com/careers",
    openings: 10,
    isPPO: true,
    isCertified: true,
    difficulty: "medium",
    acceptanceRate: 0.10,
    competitionLevel: "medium",
    companyRating: 3.9,
    internshipRating: 4.0,
    source: "curated",
    category: "startup",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Kotlin", "Jetpack Compose", "Retrofit", "Hilt", "Google Maps"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-05"),
  },
  {
    title: "Open Source Intern",
    company: "CNCF / Linux Foundation",
    companyLogo: "",
    location: "Remote, Global",
    city: "Remote",
    country: "Global",
    type: "paid",
    stipend: "$3,000 (stipend)",
    stipendMin: 3000,
    stipendMax: 3000,
    currency: "USD",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "remote",
    domain: "Open Source",
    description: "Contribute to CNCF projects like Kubernetes, Prometheus, or Envoy. Work with maintainers from top tech companies. Build your open source portfolio.",
    requirements: JSON.stringify(["Git proficiency", "Any programming language", "Open source contribution experience"]),
    skillsRequired: JSON.stringify(["Go", "Rust", "Python", "Git", "Docker", "Kubernetes"]),
    applyUrl: "https://www.linuxfoundation.org",
    openings: 30,
    isPPO: false,
    isCertified: true,
    lorAvailable: true,
    difficulty: "medium",
    acceptanceRate: 0.15,
    competitionLevel: "medium",
    companyRating: 4.6,
    internshipRating: 4.7,
    source: "curated",
    category: "research",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Go", "Rust", "Python", "Kubernetes", "Prometheus"]),
    interviewRounds: 2,
    deadline: new Date("2026-09-01"),
  },
  {
    title: "Cybersecurity Analyst Intern",
    company: "Deloitte",
    companyLogo: "https://logo.clearbit.com/deloitte.com",
    location: "Mumbai, India",
    city: "Mumbai",
    country: "India",
    type: "paid",
    stipend: "₹22,000/month",
    stipendMin: 22000,
    stipendMax: 22000,
    currency: "INR",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "onsite",
    domain: "Cybersecurity",
    description: "Work with Deloitte's cyber risk advisory team. Conduct security assessments, vulnerability scanning, and compliance audits for Fortune 500 clients.",
    requirements: JSON.stringify(["Security fundamentals", "Networking basics", "Certification preferred"]),
    skillsRequired: JSON.stringify(["Networking", "SIEM", "Python", "Linux", "Wireshark", "Nessus"]),
    applyUrl: "https://deloitte.com/careers",
    openings: 20,
    isPPO: true,
    isCertified: true,
    difficulty: "medium",
    acceptanceRate: 0.12,
    competitionLevel: "medium",
    companyRating: 4.2,
    internshipRating: 4.1,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Splunk", "Nessus", "Wireshark", "Kali Linux", "Python"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-15"),
  },
  {
    title: "Python Developer Intern",
    company: "Cognizant",
    companyLogo: "https://logo.clearbit.com/cognizant.com",
    location: "Chennai, India",
    city: "Chennai",
    country: "India",
    type: "paid",
    stipend: "₹12,000/month",
    stipendMin: 12000,
    stipendMax: 12000,
    currency: "INR",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "onsite",
    domain: "Backend",
    description: "Develop Python-based automation tools and web applications. Learn enterprise software development practices at one of the world's largest IT services companies.",
    requirements: JSON.stringify(["Python basics", "OOP concepts"]),
    skillsRequired: JSON.stringify(["Python", "Django", "SQL", "HTML/CSS", "Git", "REST APIs"]),
    applyUrl: "https://cognizant.com/careers",
    openings: 100,
    isPPO: true,
    isCertified: true,
    difficulty: "easy",
    acceptanceRate: 0.30,
    competitionLevel: "low",
    companyRating: 3.6,
    internshipRating: 3.7,
    source: "curated",
    category: "tech",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Python", "Django", "PostgreSQL", "Redis", "Docker"]),
    interviewRounds: 2,
    deadline: new Date("2026-07-22"),
  },
  {
    title: "Marketing Analytics Intern",
    company: "Zoho",
    companyLogo: "https://logo.clearbit.com/zoho.com",
    location: "Chennai, India",
    city: "Chennai",
    country: "India",
    type: "paid",
    stipend: "₹18,000/month",
    stipendMin: 18000,
    stipendMax: 18000,
    currency: "INR",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "onsite",
    domain: "Data Science",
    description: "Analyze marketing campaign data, build dashboards, and optimize user acquisition strategies. Work with Zoho's marketing analytics team.",
    requirements: JSON.stringify(["Excel/spreadsheet skills", "Basic SQL", "Interest in marketing"]),
    skillsRequired: JSON.stringify(["SQL", "Excel", "Python", "Tableau", "Google Analytics"]),
    applyUrl: "https://zoho.com/careers",
    openings: 15,
    isPPO: true,
    isCertified: true,
    difficulty: "easy",
    acceptanceRate: 0.20,
    competitionLevel: "low",
    companyRating: 4.2,
    internshipRating: 4.3,
    source: "curated",
    category: "tech",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["SQL", "Python", "Tableau", "Google Analytics", "Excel"]),
    interviewRounds: 2,
    deadline: new Date("2026-07-25"),
  },
  {
    title: "Flutter Developer Intern",
    company: "Cleartrip",
    companyLogo: "https://logo.clearbit.com/cleartrip.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹22,000/month",
    stipendMin: 22000,
    stipendMax: 22000,
    currency: "INR",
    duration: "6 months",
    durationWeeks: 24,
    workMode: "hybrid",
    domain: "Mobile",
    description: "Build cross-platform mobile apps for India's leading travel platform. Work on flight booking, hotel search, and travel itinerary features.",
    requirements: JSON.stringify(["Dart/Flutter basics", "Mobile development interest"]),
    skillsRequired: JSON.stringify(["Flutter", "Dart", "REST APIs", "State Management", "Firebase"]),
    applyUrl: "https://cleartrip.com/careers",
    openings: 8,
    isPPO: true,
    isCertified: true,
    difficulty: "medium",
    acceptanceRate: 0.12,
    competitionLevel: "medium",
    companyRating: 4.0,
    internshipRating: 4.1,
    source: "curated",
    category: "startup",
    hiringSpeed: "fast",
    techStack: JSON.stringify(["Flutter", "Dart", "Firebase", "REST APIs", "Git"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-10"),
  },
  {
    title: "AI Ethics Research Intern",
    company: "Accenture",
    companyLogo: "https://logo.clearbit.com/accenture.com",
    location: "Bangalore, India",
    city: "Bangalore",
    country: "India",
    type: "paid",
    stipend: "₹25,000/month",
    stipendMin: 25000,
    stipendMax: 25000,
    currency: "INR",
    duration: "3 months",
    durationWeeks: 12,
    workMode: "hybrid",
    domain: "AI/ML",
    description: "Research AI fairness, bias detection, and ethical AI frameworks. Help Accenture develop responsible AI practices for enterprise clients.",
    requirements: JSON.stringify(["AI/ML knowledge", "Research skills", "Ethics background preferred"]),
    skillsRequired: JSON.stringify(["Python", "Machine Learning", "NLP", "Ethics", "Research", "Statistics"]),
    applyUrl: "https://accenture.com/careers",
    openings: 10,
    isPPO: true,
    isCertified: true,
    lorAvailable: true,
    difficulty: "medium",
    acceptanceRate: 0.10,
    competitionLevel: "medium",
    companyRating: 4.1,
    internshipRating: 4.0,
    source: "curated",
    category: "fortune500",
    hiringSpeed: "normal",
    techStack: JSON.stringify(["Python", "Jupyter", "Hugging Face", "Scikit-learn"]),
    interviewRounds: 3,
    deadline: new Date("2026-08-05"),
  },
];

async function main() {
  console.log("Seeding internships...");

  // Clear existing
  await prisma.internship.deleteMany();

  for (const internship of INTERNSHIPS) {
    await prisma.internship.create({ data: internship });
  }

  console.log(`Seeded ${INTERNSHIPS.length} internships.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
